### ISSUE TITLE
Plone 5 get_registry_record error 

### ISSUE THREAD

**Issue by leejoramo** [collective/collective.autoscaling#2]
I get the following error on a Plone 5 site trying /@@resize-images

> Traceback (innermost last):
>   Module ZPublisher.Publish, line 138, in publish
>   Module ZPublisher.mapply, line 77, in apply
>   Module ZPublisher.Publish, line 48, in call_object
>   Module collective.autoscaling.browser.resizing, line 24, in **call**
>   Module collective.autoscaling.resizing, line 30, in scale_images
>   Module collective.autoscaling.resizing, line 14, in get_max_size
>   Module collective.autoscaling.utils, line 34, in get_autoscaling_settings
> TypeError: get_registry_record() takes at most 1 argument (2 given)

**Comment by bsuttor** [comment]
Hi,
It's a problem with version of plone.api,
you have to pin plone.api >= 1.4.11
